### ISSUE TITLE
ImportError: cannot import name CatalogSource

### ISSUE THREAD

**Issue by khink** [plone/plone.app.event#151]
On a fresh Plone 4.3.2 site, plone.app.contenttypes 1.2a1 (which should work on Plone 4.3 right?) pulls in plone.app.events 1.2.1, which on instance startup gives:

```
ZopeXMLConfigurationError: File "/home/kees/.buildout/eggs/plone.app.contenttypes-1.2a1-py2.6.egg/plone/app/contenttypes/configure.zcml", line 10.2-10.37
ZopeXMLConfigurationError: File "/home/kees/.buildout/eggs/plone.app.event-1.2.1-py2.6.egg/plone/app/event/configure.zcml", line 23.2-23.33
ZopeXMLConfigurationError: File "/home/kees/.buildout/eggs/plone.app.event-1.2.1-py2.6.egg/plone/app/event/portlets/configure.zcml", line 13.4-20.10
ImportError: cannot import name CatalogSource
```

Pinning plone.app.event = 1.2 works.
